environment:
  PYTHON_HOME: "C:\\Python37"
  CONAN_OPTIONS: "*:shared=True"

  matrix:
    - MINGW_CONFIGURATIONS: '8@x86@dwarf2@posix'
      CONAN_BUILD_REQUIRES: 'msys2_installer/latest@bincrafters/stable'
      CONAN_BUILD_TYPES: Release
      V: 1
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CONAN_VISUAL_VERSIONS: 14
      CONAN_BUILD_TYPES: "Release,Debug"
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#      CONAN_VISUAL_VERSIONS: 15
#      CONAN_BUILD_TYPES: "Release,Debug"

install:
  - git submodule update --init --recursive --depth=1
  - set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
  - conan-shared-scripts\install_conan.bat

build_script:
  - python conan-shared-scripts/build.py --shared
